FROM nginx
RUN echo '<!DOCTYPE html> \
<html> \
<head> \
<style> \
body { \
    background-color: lightpink; \
    margin: 0; \
    padding: 0; \
    font-family: Arial, sans-serif; \
} \
.header { \
    color: black; \
    text-align: center; \
} \
</style> \
</head> \
<body> \
<div class="header">This is the second web server</div> \
</body> \
</html>' > /usr/share/nginx/html/index.html
